name: Mypy and Pytest

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PDM and Python (version 3.12)
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.12'
          cache: true
          cache-dependency-path: |
            ./pdm.lock
        
      - name: Install dependencies
        run: pdm install --dev

      - name: Run Mypy (Type Checking)
        run: |
          pdm run mypy .  # Run mypy on your project directory

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up PDM and Python (version 3.12)
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.12'
          cache: true
          cache-dependency-path: |
            ./pdm.lock
        
      - name: Install dependencies
        run: pdm install --dev

      - name: Run Pytest (Tests)
        run: |
          pdm run pytest --cov=./ --cov-report xml
      
      - name: Report results to DeepSource
        run: |
          # Tests have finished and a test coverage report is available

          # Install deepsource CLI
            curl https://deepsource.io/cli | sh

          # From the root directory, run the report coverage command
            ./bin/deepsource report --analyzer test-coverage --key python --value-file ./path/to/report

        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
